### ISSUE TITLE
DDOS Protection

### ISSUE THREAD

**Issue by netpro25** [stanford-rc/dell_warranty#1]
It looks like Dell has no implemented DDOS protection through Akamai which will show a timeout page before advancing to the overview page. Therefore results won't be returned consistently. Not sure if you've experienced the same.

Here's the DDOS protection page.

`  <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Challenge Validation</title>
        <link rel="stylesheet" type="text/css" href="/_sec/cp_challenge/sec-3-8.css">
        <script type="text/javascript">function cp_clge_done(){location.reload(true);}</script>
        <script src="/_sec/cp_challenge/sec-cpt-int-3-8.js" async defer></script>
        <script type="text/javascript">sessionStorage.setItem('data-duration', 30);</script>
      </head>
      <body>
        <div class="sec-container">
          <div id="sec-text-container"><iframe id="sec-text-if" class="custmsg" src="/_sec/cca/esupp/index.htm"></iframe></div>
          <div id="sec-if-container">
            <iframe id="sec-cpt-if" class="crypto" data-key="" data-duration=30 src="/_sec/cp_challenge/ak-challenge-3-8.htm"></iframe>
          </div>
        </div>
      </body>
    </html>`

**Comment by kcgthb** [comment]
Yep, I've seen that from some hosts, not really sure how to avoid them, though :\

**Comment by netpro25** [comment]
Thanks for the quick response!

**Comment by netpro25** [comment]
So I think I found the solution, by changing the _abck cookie value to the cookie value provided by dell when I log into my account (from chrome devtools) I'm no longer receiving the error mentioned previously. Do you think allowing to provide this cookie value as a command line argument would be helpful? This way when the cookie needs to be updated there's no need to modify the script.

**Comment by kcgthb** [comment]
I though about it, but unfortunately, that doesn't seem to be very robust. Even with a fresh cookie, running the script a few times in a row will trigger the "Challenge validation" page. :\

**Comment by netpro25** [comment]
How many devices are you running through the script before you run into issues? I have only a few hundred to check.

**Comment by kcgthb** [comment]
About 3 :(
```
$ rc=0; while [[ $rc == 0 ]]; do ./dell_warranty.sh $SVCTAG &>/dev/null; rc=$?; echo $rc; sleep 1; done
0
0
0
1
```

**Comment by kcgthb** [comment]
> Do you think allowing to provide this cookie value as a command line argument would be helpful? This way when the cookie needs to be updated there's no need to modify the script.

Done in e325722, you can now set the `DELL_ABCK` environment variable to pass your own cookie value to the script.
